### ISSUE TITLE
Does not work with Pokémon GO 0.37.0

### ISSUE THREAD

**Issue by pperle** [chuparCh0pper/PoGoIV_xposed#23] opened 2016-09-11 09:10 UTC
In Pokémon GO 0.37.0 the NiaNet class has changed. "doSyncRequest" & "readDataSteam" are no longer available.

``` java
package com.nianticlabs.nia.network;

import java.nio.ByteBuffer;

public class NiaNet {
    private static final int CHUNK_SIZE = 32768;
    static ThreadLocal<ByteBuffer> readBuffer = new ThreadLocal() {
        protected ByteBuffer initialValue() {
            return ByteBuffer.allocateDirect(CHUNK_SIZE);
        }
    };
    private static final ThreadLocal<byte[]> threadChunk = new ThreadLocal() {
        protected byte[] initialValue() {
            return new byte[CHUNK_SIZE];
        }
    };
}
```

**Comment by ELynx** [comment] 2016-09-11 12:14
All I can recommend is still try to beat HttpURLConnection. See my module for what I did, MITMing on IO streams. I used doSyncRequest and readDataStream to determine if thread is NiaNet thread or not, so may be now you have to try to parse every package, and see which of them are PoGo game related and which are not.

**Comment by dneal12** [comment] 2016-09-11 14:25
I am anxiously awaiting a fix to this as well.  I have systemless root so the app and exposed seem to be working fine but both this module and Pokemon go IV checker seem to not work.... Yet.

**Comment by pperle** [comment] 2016-09-11 19:33
I had a look thorugh the hole com.nianticlabs.nia package and couldn't find any connections.

This is watch it used to look https://github.com/applidium/PokemonGo_Android_RE/blob/master/android/app/src/main/java/com/nianticlabs/nia/network/NiaNet.java .

**Comment by hirenshah** [comment] 2016-09-12 08:26
Would be good to see this working again :-)

**Comment by ELynx** [comment] 2016-09-12 09:01
@chuparCh0pper I usually examined never versions, including 0.35.0, myself. Smali looks far worse than Java OFC, but keeping that as reference, it is pretty understandable, especially when calls to libraries are made.

HttpURLConnection is in Java library for platform.
Look at [Injector](https://github.com/ELynx/pokemon-go-xposed-mitm/blob/master/app/src/main/java/com/elynx/pogoxmitm/Injector.java) from my module, I hook getOutputStream and getInputStream. Does something like this works?

I managed to install Andy 5.0 and systemless root on my Sams Note 3, looking for XPosed now. Looks like Sams "tweaked" 5.0 so hard that regular and systemless XPosed are not working at all.

**Comment by HexDestroyer** [comment] 2016-09-12 09:47
@ELynx Hey! I loved your work.
I managed to get systemless xposed working on my OnePlus 3 with magisk and phh's su.
It seems the modules are loading but because of "doSyncRequest" & "readDataSteam" removal they are no longer working.
I am not an experienced programmer, but I will try to tweak your Injector to make things work again.

Also I am sorry for your problems. Have you looked into installing cyanogen on your Note?

**Comment by ELynx** [comment] 2016-09-12 12:43
@HexDestroyer Great news, with modules loading you can do research again. In hooks to stream getters, just remove checks for niaRequest and niaResponse, enable MitM streams always. This way you will dump all content that goes via HttpURLConnection. Not sure that else may use it.

Dump it into file may be, or mirror to wireshark. I had heard that protocol is changed too, so decoders may fail.

I looked through CM12 and CM13 ROMs. They either have RIL but lack something else, or have a lot of features but have faulty RIL (or just have faulty everything and WIP). Since I have only one phone I can't afford to lose functions. May be I will make systemless XPosed for Sams now, for all that may be.

**Comment by HexDestroyer** [comment] 2016-09-12 22:19
@ELynx Long story short, it works!
It seems protocol changed just for authentication. I haven't really analyzed anything, but I've came across [this reddit post ](https://www.reddit.com/r/pokemongodev/comments/526b96/unconfirmed_protobuf_seem_to_have_changed_a_lot/)referencing in the comments [this image](http://imgur.com/Y52GstV).
So yeah, I just now had the time to recompile with the suggested changes.
I've removed the hooks to doSyncRequest and readDataSteam (made the module crash as it didn't find them), and I've removed checks for niaRequest and niaResponse.
I didn't analyze the traffic or anything, but I had made changes to dump to a file the pokémon's IV and the WildPokémon responses and those still work!

I am very sorry for your phone. I hope you will find a solution.

**Comment by andrerdxd** [comment] 2016-09-13 06:00
Any news?

**Comment by sloppycoffee** [comment] 2016-09-13 14:18
@HexDestroyer That is awesome news! Can't wait to see this module back up and running.. Having that instant success or escape is so nice!

**Comment by ELynx** [comment] 2016-09-13 17:01
@HexDestroyer Great news!
I am sure community will find a way to tackle this problem. I suggest to look for any possibilities to determine responses and requests going from/to NiaNet (or whatnot it is now).
Make a github fork, publish your code, I am sure that if you want, you can handle this.

**Comment by Geckohazard** [comment] 2016-09-14 16:27
Just here to show support. I love this module and can't wait to see it back. Those of us who can't make something like this are all rooting for you.

**Comment by riththerift** [comment] 2016-09-14 18:48
Here to show support as well. I missed this module so much! Everything I load up Pokémon Go, it makes me sad seeing no IV information.

**Comment by GeoWebDevCom** [comment] 2016-09-16 07:57
Any update on this :)

**Comment by xomikronx** [comment] 2016-09-23 15:44
Still nothing guys?  Is there a thread where this is being actively discussed that I can follow?  I tried the discord chats, but nothing.

**Comment by HexDestroyer** [comment] 2016-09-23 15:48
I'm sorry. I am in the process of moving at the moment and will be without internet for a while.
Will work on it as soon as I can get back on my feet.

**Comment by sloppycoffee** [comment] 2016-09-23 16:31
I actually just rolled back to 0.35 and the module still works.

**Comment by FreedomMercenary** [comment] 2016-09-24 19:22
I'll see if I can take a look at this when I get some time or if my work on the IV checker from @ELynx is helpful.  I don't know if he published the changes to the Xposed repository, but he did merge them into his release (right-now) branch.  That work is at FreedomMercenary/pokemon-go-xposed-mitm/PoGo-0.37-Fix

**Comment by ELynx** [comment] 2016-09-25 11:10
@FreedomMercenary Hi, yes, I merged your fix into repo. I can add you as developer to the module, so you can publish your version there. Just write that it is under your control. Strange you didn't see my reply [here](https://github.com/ELynx/pokemon-go-xposed-mitm/issues/24). I will also need to send you signing keys for the app. PM me at xda-devs, nick is EduardLynx.

**Comment by riththerift** [comment] 2016-09-25 14:15
If you guys aren't able to get Pokémon Go 0.37 to work with Xposed, you may want to check out xda thread: http://forum.xda-developers.com/showthread.php?t=3388268.  See post 2117,  2120 & 2283. 

Right now,  I have Xposed and root active and able to play Pokémon Go 0.37.

**Comment by xomikronx** [comment] 2016-09-25 23:51
I've got xposed working with magisk working since the .37 update.  PoGoIV and Pokemon GO IV checker both do not work due to the API changes though.  Am I misunderstanding or is it working for you you @xstahsie ?

@xstahsie Do those steps work on .39.1?

**Comment by xomikronx** [comment] 2016-09-26 15:18
Niantic is forcing .39 now.  No more IV Checker.  :(

**Comment by taririk** [comment] 2016-09-26 16:24
Since we can successfully hook into the Input/OutputStream methods (refer to @FreedomMercenary's commit on ELynx repo), I am trying to inject directly the actual doSyncRequest" & "readDataSteam" methods (taken from 0.35) into it. But since I am a total noob with java, I don't know how to make it work... or if it would actually work. Any thoughts on that approach?

**Comment by pperle** [comment] 2016-09-26 20:48
Big shoutout to @igoticecream and his xposed modul https://github.com/igoticecream/Snorlax/ .
I just installed it and notification when you encounter and toast when catching pokémon works.
I encourage everybody to download his [module](http://repo.xposed.info/module/com.icecream.snorlax).

**Comment by sloppycoffee** [comment] 2016-09-26 21:03
Nice. Downloaded and giving it a shot. Does the original magisk workaround
still work for 0.39?

**Comment by pperle** [comment] 2016-09-26 21:05
@slayorktc I think you have to switch to suhide & systemless v86.2
https://www.reddit.com/r/pokemongodev/comments/53ood1/migrate_from_magisk_phhs_superuser_xposed/

**Comment by sloppycoffee** [comment] 2016-09-26 21:07
Thanks for the link. Ill get on it.

**Comment by sloppycoffee** [comment] 2016-09-26 22:05
That link worked perfect. Up and running again with the latest version. The
snorlax module showed the escape/sucess toast message but the IV
notification didn't seem to roll in. I only tested it with one pokemon.
Will test it more when more come around.

**Comment by xomikronx** [comment] 2016-09-26 23:27
Snorlax module worked perfectly.  Shows IV, ATK, DEF, STA, Level, Attack types and percentages for pokeball.

**Comment by riththerift** [comment] 2016-09-26 23:39
The Snorlax module doesn't seem to work on my Nexus 6p. Am I doing something wrong?

**Comment by xomikronx** [comment] 2016-09-26 23:46
@xstahsie what are your exact steps?

**Comment by wjoshua1984** [comment] 2016-09-26 23:58
@xstahsie I had to reboot a few times, not sure why, maybe because I just switched to suhide

**Comment by riththerift** [comment] 2016-09-26 23:59
@xomikronk I downloaded the module, enabled it in Xposed, rebooted my phone, and start Pokémon Go. 

I have a stock 6.0.1 ROM with suhide, Xposed framework 86.2 systemless, and magisk v6. My other modules work just fine (e.g RecentApp clear and NeoPower menu).

**Comment by xomikronx** [comment] 2016-09-27 00:03
These were my exact steps:

uninstall xposed systemless v86.5
reboot
uninstall magisk
reboot
reflash magisk v6
flash supersu v2.76(magisk version)
from terminal: echo "SYSTEMLESS=true > /data/.supersu
flash supersu v2.78
reboot
flash xposed systemless v86.2
reboot
flash suhide 0.53
reboot system

I might have over rebooted, but it worked.

**Comment by xomikronx** [comment] 2016-09-27 00:06
Anyone know a GPS spoofer that works on .39 yet?

**Comment by mazzod** [comment] 2016-09-27 00:10
@xomikronx I think FlyGPS or GPS Joystick are working good

**Comment by mazzod** [comment] 2016-09-27 00:20
I have a question guys. I moved from phh's superuser and xposed systemless 86.5 to superSU systemless and xposed 86.2. For my curiosity I've installed magisk Manager and I see that the root toogle is always unchecked and if I try to enable it, it go back to unchecked. It's normal?
Back to OT, I installed the Snorlax module and all works fine, I can't wait a new update with new content! :smiley:

**Comment by taririk** [comment] 2016-09-27 00:57
Great implementation @igoticecream. Works like a charm! I been trying to hook that HttpURL call but cant make it work. Yours does it perfectly. Starred!

**Comment by riththerift** [comment] 2016-09-27 01:11
@xomikronk that's exactly what I did. 

@igoticecream would you know why your module is not working on a Nexus 6P with a stock 6.0.1 ROM? Other modules I have downloaded works fine.

**Comment by sloppycoffee** [comment] 2016-09-27 01:11
I uninstalled the magisk manager. Don't think it's needed anymore.

**Comment by igoticecream** [comment] 2016-09-27 01:55
@xstahsie if you use suhide, ensure pokemon go id is not listed (otherwise, it wont load the module). Happened with other module im developing, i added snapchat to suhide and it stopped loading the module.

**Comment by riththerift** [comment] 2016-09-27 02:39
@igoticecream thanks! That was it. It worked after removing the Pokémon Go ID from suhide and rebooting the phone. I want to thank everyone here for making this possible.

**Comment by xomikronx** [comment] 2016-09-27 13:47
Only thing left that is missing for me is the Pokemon IV checker.  (seeing this information in the pokemon inventory)  As far as I know, there isn't a working module yet?

**Comment by riththerift** [comment] 2016-09-27 14:00
@xomikronx that would be awesome to be able to see IV info in the inventory. Perhaps @igoticecream is working on something like that. Who knows.

**Comment by igoticecream** [comment] 2016-09-27 14:02
Hello @xstahsie.

Yes is coming, in fact @chuparCh0pper is already working in that feature.

**Comment by riththerift** [comment] 2016-09-27 14:06
@igoticecream @chuparCh0pper that's wonderful news! Keep up the good work guys.

**Comment by xomikronx** [comment] 2016-09-27 14:19
@igoticecream @chuparCh0pper are you making it a part of Snorlax or a separate module?

**Comment by igoticecream** [comment] 2016-09-27 14:23
@xomikronx that feature is being developed here

https://github.com/chuparCh0pper/Snorlax

**Comment by xomikronx** [comment] 2016-09-27 14:25
thanks!

**Comment by riththerift** [comment] 2016-09-27 15:36
Thanks!

**Comment by Err0r404** [comment] 2016-09-29 09:50
@igoticecream Do you know when this feature will be released ?

**Comment by FreedomMercenary** [comment] 2016-09-29 18:00
I have opened a merge request to add compatibility with 0.37+.  I also published the ELynx MITM module again into the Xposed repository as I've been using it for a couple of weeks with no issue.  @chuparCh0pper if you're open to it, I'd like to work on incorporating his MITM logic to change the name of each Pokemon to the IV formatted values as an additional option.

**Comment by riththerift** [comment] 2016-09-29 18:21
@FreedomMercenary 
Pokémon Go Xposed Mitm v1. 3.2 force closes as soon as I open it.  

I am using a stock 6.0.1 ROM on a Nexus 6P. It has Magisk, systemless Xposed, and suhide.

**Comment by FreedomMercenary** [comment] 2016-09-29 18:47
Can you send me a copy of your Xposed log?

**Comment by mazzod** [comment] 2016-09-29 18:50
On my side all is working good. I can see the IV's on pokemon page, I haven't already tested if even the timer for the lured pokestop is working. I'm on Mm 6.0.1 on shield tablet

**Comment by pperle** [comment] 2016-09-29 18:56
@FreedomMercenary Thank you I will test the code and merge
@xstahsie go into permissions and enable storage permission

**Closed as completed** 2016-09-29 19:08 UTC

**Comment by riththerift** [comment] 2016-09-29 19:19
@chuparCh0pper Thanks. All is working now.

**Comment by pperle** [comment] 2016-09-29 19:22
@FreedomMercenary you can change/add whatever you want 😉 
Also have a look at https://github.com/igoticecream/Snorlax/ is has a much cleaner project structure.
