### ISSUE TITLE
[bug] does not show messages on android 4.4.2 and pokemon go v0.35.0 

### ISSUE THREAD

**Issue by Xelwon** [chuparCh0pper/PoGoIV_xposed#12] opened 2016-08-30 21:16 UTC
It does not work on android 4.4.2 and pokemon go v0.35.0.
I have:
app_process 58
XposedBridge.jar 54
pogoiv v1.4 module activated
on app pogoiv enabled module too,
pokemon go v0.35.0

**Comment by pperle** [comment] 2016-08-30 21:32
Are no notifications shown at all? 

Heads Up Notifications were introduced in Lollipop as far as I know try this xposed module for KitKat http://repo.xposed.info/module/com.mohammadag.headsupenabler

**Comment by deana14** [comment] 2016-08-31 02:48
Version 1.2.3 was working perfectly on my KK 4.4. Since the 1.3 release (on both pogo v0.33.0 and v0.35.0)  however, the module just stopped working altogether - No notifications/toasts at all. I've enabled the module+reboot etc.. and even uninstall+reinstall several times but nothing seems to work. With the recent 1.4 update, the "added icon" never even appeared in the launcher and still no luck with the notifications.

Rolling back to 1.2.3 was working for a while until a few days ago when I noticed that the notification stopped showing pokemon moves/level.

I have noticed that many others have been reporting the same issue on 4.4\* on the module's reddit page, yet haven't seen any reply on them. Could you please compile a version that's compatible with 4.4*? (app_process 58, XposedBridge.jar 54).

**Comment by pperle** [comment] 2016-08-31 08:29
@deana14 Thank you for the detailed report. With me being on holiday I'm sorry for abandoning the reddit thread.
Please uninstall the old version and install [this one](https://drive.google.com/file/d/0BzPOjBd9NuJIcW9GRnpSUndoTDQ/view?pref=2&pli=1). It is compiled as debug so logging should be activated.
After a reboot please start the game and post your xposed logs.

I think the problem is in loading the preferences. This is a known bug of https://github.com/rovo89/XposedBridge/issues/102 .

**Comment by Xelwon** [comment] 2016-08-31 14:13
I installed "Head ups Notifications" and debug.apk.
I activated those modules.
I restarted the phone.
I tried pokemgon go with same results. no messages.
The xposed log is the next:

```
samsung/samsung:4.4.2/KOT49H/3.6.1.0729:userdebug/test-keys'
Loading modules from /data/app/de.chuparch0pper.android.xposed.pogoiv-1.apk
  Loading class de.chuparch0pper.android.xposed.pogoiv.IVChecker
java.lang.ClassNotFoundException: Didn't find class "de.chuparch0pper.android.xposed.pogoiv.IVChecker" on path: DexPathList[[zip file "/data/app/de.chuparch0pper.android.xposed.pogoiv-1.apk"],nativeLibraryDirectories=[/system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:421)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)

```

**Comment by Xelwon** [comment] 2016-08-31 14:16
Loading modules from /data/app/de.elfinlazz.android.xposed.pokemongo-1.apk
  Loading class de.elfinlazz.android.xposed.pokemongo.PokemonGo
Can't Read Stream!!java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
RequestId warning 0
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
Can't Read Stream!!java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestId warning 0
Can't Read Stream!!java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
ResponseEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
RequestEnvelope parsing failed com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).

**Comment by Xelwon** [comment] 2016-08-31 14:23
:O, v1.2.3 works perfercly. Thanks deana14, for the information.

**Comment by pperle** [comment] 2016-08-31 21:26
> java.lang.ClassNotFoundException: Didn't find class "de.chuparch0pper.android.xposed.pogoiv.IVChecker" on path: DexPathList[[zip file "/data/app/de.chuparch0pper.android.xposed.pogoiv-1.apk"],nativeLibraryDirectories=[/system/lib]]

This does not look normal. Looks like I could not find "de.chuparch0pper.android.xposed.pogoiv.IVChecker". Well I try to get my hands on a 4.4.2 this weekend.

**Comment by Noside69** [comment] 2016-09-01 02:08
I've same issues with Xelwon.
Did everything stated above, still no notification.
Running on KitKat 4.4.4 - version 1.2.3 is working though.

**Comment by pperle** [comment] 2016-09-11 19:17
I guess the problem was MultiDex & POGOProtos. Now MultiDex has been droped, so give it a try.
I'm going to close this issue because of https://www.reddit.com/r/pokemongodev/comments/5294zs/0370_kill_kitkat_device_with_root/ .

**Closed as completed by pperle** 2016-09-11 19:17 UTC
Labels: bug
